# SuiPatron Smart Contract Publisher (PowerShell)
# Publishes the contract and automatically updates environment variables

$ErrorActionPreference = "Continue"  # Don't stop on errors

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$EnvFile = Join-Path $ScriptDir "..\..\..\apps\suipatron\.env.local"
$OutputFile = Join-Path $ScriptDir "publish-output.txt"

Write-Host "🚀 Publishing SuiPatron smart contract..." -ForegroundColor Cyan
Write-Host ""

# Build the contract first
Write-Host "📦 Building contract..." -ForegroundColor Yellow
sui move build

Write-Host ""
Write-Host "🔄 Publishing to SUI Testnet..." -ForegroundColor Yellow
Write-Host ""

# Publish and save output
sui client publish --gas-budget 200000000 2>&1 | Tee-Object -FilePath $OutputFile

Write-Host ""
Write-Host "✅ Publish complete!" -ForegroundColor Green
Write-Host ""

# Read the output file
$output = Get-Content $OutputFile -Raw

# Extract Package ID - try multiple patterns
$packageId = $null

# Pattern 1: Look for "PackageID" or "Package ID"
if ($output -match '(?i)package\s*id[:\s]+(\w+[a-fA-F0-9]{64})') {
    $packageId = $matches[1]
}

# Pattern 2: Look in Published Objects section
if (-not $packageId -and $output -match 'Published Objects.*?(0x[a-fA-F0-9]{64})') {
    $packageId = $matches[1]
}

# Pattern 3: First occurrence of 0x followed by 64 hex chars
if (-not $packageId -and $output -match '(0x[a-fA-F0-9]{64})') {
    $packageId = $matches[1]
}

# Extract Platform ID - look for Platform in Created Objects
$platformId = $null
if ($output -match 'Platform') {
    # Get context around "Platform" and find object ID
    $platformMatches = [regex]::Matches($output, '(0x[a-fA-F0-9]{64})[\s\S]{0,200}Platform|Platform[\s\S]{0,200}(0x[a-fA-F0-9]{64})')
    if ($platformMatches.Count -gt 0) {
        foreach ($match in $platformMatches[0].Groups) {
            if ($match.Value -match '^0x[a-fA-F0-9]{64}$') {
                $platformId = $match.Value
                break
            }
        }
    }
}

Write-Host "📝 Extracted values:" -ForegroundColor Cyan
Write-Host "   Package ID:  $packageId"
Write-Host "   Platform ID: $platformId"
Write-Host ""

if (-not $packageId) {
    Write-Host "❌ Error: Could not extract Package ID from output" -ForegroundColor Red
    Write-Host "   Please check $OutputFile and update manually"
    Write-Host ""
    Write-Host "   Looking for pattern like: 0x followed by 64 hex characters"
    exit 1
}

# Create directory if it doesn't exist
$envDir = Split-Path -Parent $EnvFile
if (-not (Test-Path $envDir)) {
    New-Item -ItemType Directory -Path $envDir -Force | Out-Null
}

# Create or update .env.local
Write-Host "📄 Updating $EnvFile..." -ForegroundColor Yellow

# Create file if it doesn't exist
if (-not (Test-Path $EnvFile)) {
    @"
# SuiPatron Environment Variables
# Auto-generated by publish script

"@ | Out-File -FilePath $EnvFile -Encoding UTF8
}

# Read existing env file
$envContent = Get-Content $EnvFile -ErrorAction SilentlyContinue

# Function to update or add env variable
function Update-EnvVar {
    param($Key, $Value, $Content)

    $found = $false
    $newContent = @()

    if ($Content) {
        foreach ($line in $Content) {
            if ($line -match "^${Key}=") {
                $newContent += "${Key}=${Value}"
                $found = $true
                Write-Host "   ✓ Updated ${Key}" -ForegroundColor Green
            } else {
                $newContent += $line
            }
        }
    }

    if (-not $found) {
        $newContent += "${Key}=${Value}"
        Write-Host "   ✓ Added ${Key}" -ForegroundColor Green
    }

    return $newContent
}

# Update Package ID
$envContent = Update-EnvVar "NEXT_PUBLIC_PACKAGE_ID" $packageId $envContent

# Update Platform ID if found
if ($platformId) {
    $envContent = Update-EnvVar "NEXT_PUBLIC_PLATFORM_ID" $platformId $envContent
} else {
    Write-Host "   ⚠ Platform ID not found - you may need to add it manually" -ForegroundColor Yellow
}

# Ensure network is set
$hasNetwork = $envContent | Where-Object { $_ -match "^NEXT_PUBLIC_SUI_NETWORK=" }
if (-not $hasNetwork) {
    $envContent += "NEXT_PUBLIC_SUI_NETWORK=testnet"
    Write-Host "   ✓ Added NEXT_PUBLIC_SUI_NETWORK" -ForegroundColor Green
}

# Write back to file
$envContent | Out-File -FilePath $EnvFile -Encoding UTF8

Write-Host ""
Write-Host "✨ Environment file updated!" -ForegroundColor Green
Write-Host ""
Write-Host "📋 Current configuration:" -ForegroundColor Cyan
if (Test-Path $EnvFile) {
    Get-Content $EnvFile | Where-Object { $_ -match "NEXT_PUBLIC" }
}
Write-Host ""
Write-Host "💾 Full publish output saved to: $OutputFile" -ForegroundColor Gray
Write-Host ""
Write-Host "🎯 Next steps:" -ForegroundColor Yellow
Write-Host "   1. Verify the values above are correct"
Write-Host "   2. Restart your frontend: cd apps\suipatron && npm run dev"
Write-Host "   3. Test at http://localhost:3001/explore"
Write-Host ""
