#!/bin/bash

# SuiPatron Smart Contract Publisher
# Publishes the contract and automatically updates environment variables

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../../../apps/suipatron/.env.local"
OUTPUT_FILE="$SCRIPT_DIR/publish-output.txt"

echo "🚀 Publishing SuiPatron smart contract..."
echo ""

# Build the contract first
echo "📦 Building contract..."
sui move build

echo ""
echo "🔄 Publishing to SUI Testnet..."
echo ""

# Publish and save output
sui client publish --gas-budget 200000000 2>&1 | tee "$OUTPUT_FILE"

echo ""
echo "✅ Publish complete!"
echo ""

# Extract Package ID - try multiple patterns
PACKAGE_ID=""

# Pattern 1: Look for PackageID in the output
PACKAGE_ID=$(grep -i "packageid" "$OUTPUT_FILE" | grep -o "0x[a-f0-9]\{64\}" | head -1)

# Pattern 2: Look in Published Objects section
if [ -z "$PACKAGE_ID" ]; then
    PACKAGE_ID=$(grep -A 10 "Published Objects" "$OUTPUT_FILE" | grep -o "0x[a-f0-9]\{64\}" | head -1)
fi

# Pattern 3: Any 0x followed by 64 hex chars
if [ -z "$PACKAGE_ID" ]; then
    PACKAGE_ID=$(grep -o "0x[a-f0-9]\{64\}" "$OUTPUT_FILE" | head -1)
fi

# Extract Platform ID - look for Platform in Created Objects
PLATFORM_ID=""
if grep -q "Platform" "$OUTPUT_FILE"; then
    # Get lines around "Platform"
    PLATFORM_ID=$(grep -B 3 -A 3 "Platform" "$OUTPUT_FILE" | grep -o "0x[a-f0-9]\{64\}" | head -1)
fi

echo "📝 Extracted values:"
echo "   Package ID:  $PACKAGE_ID"
echo "   Platform ID: $PLATFORM_ID"
echo ""

if [ -z "$PACKAGE_ID" ]; then
    echo "❌ Error: Could not extract Package ID from output"
    echo "   Please check $OUTPUT_FILE and update manually"
    echo ""
    echo "   Looking for pattern like: 0x followed by 64 hex characters"
    exit 1
fi

# Create directory if it doesn't exist
ENV_DIR="$(dirname "$ENV_FILE")"
mkdir -p "$ENV_DIR"

# Create or update .env.local
echo "📄 Updating $ENV_FILE..."

# Create file if it doesn't exist
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << EOF
# SuiPatron Environment Variables
# Auto-generated by publish script

EOF
fi

# Function to update or add env variable (using temp file for compatibility)
update_env_var() {
    local key=$1
    local value=$2
    local file=$3
    local temp_file="${file}.tmp"

    if grep -q "^${key}=" "$file" 2>/dev/null; then
        # Update existing - use temp file for compatibility
        grep -v "^${key}=" "$file" > "$temp_file"
        echo "${key}=${value}" >> "$temp_file"
        mv "$temp_file" "$file"
        echo "   ✓ Updated ${key}"
    else
        # Add new
        echo "${key}=${value}" >> "$file"
        echo "   ✓ Added ${key}"
    fi
}

# Update Package ID
update_env_var "NEXT_PUBLIC_PACKAGE_ID" "$PACKAGE_ID" "$ENV_FILE"

# Update Platform ID if found
if [ -n "$PLATFORM_ID" ]; then
    update_env_var "NEXT_PUBLIC_PLATFORM_ID" "$PLATFORM_ID" "$ENV_FILE"
else
    echo "   ⚠ Platform ID not found - you may need to add it manually"
fi

# Ensure network is set
if ! grep -q "^NEXT_PUBLIC_SUI_NETWORK=" "$ENV_FILE" 2>/dev/null; then
    echo "NEXT_PUBLIC_SUI_NETWORK=testnet" >> "$ENV_FILE"
    echo "   ✓ Added NEXT_PUBLIC_SUI_NETWORK"
fi

echo ""
echo "✨ Environment file updated!"
echo ""
echo "📋 Current configuration:"
if [ -f "$ENV_FILE" ]; then
    grep "NEXT_PUBLIC" "$ENV_FILE" 2>/dev/null || echo "   (No NEXT_PUBLIC vars found)"
else
    echo "   ⚠ File was not created: $ENV_FILE"
fi
echo ""
echo "💾 Full publish output saved to: $OUTPUT_FILE"
echo ""
echo "🎯 Next steps:"
echo "   1. Verify the values above are correct"
echo "   2. Restart your frontend: cd apps/suipatron && npm run dev"
echo "   3. Test at http://localhost:3001/explore"
echo ""
